### PR TITLE
docs: add Google Cloud Storage publisher docs

### PR DESCRIPTION
**Pull request by mahnunchik**
Documentation for: https://github.com/electron-userland/electron-forge/pull/1752

### CODE REVIEW

**Comment by mahnunchik** [comment]
ping

**Comment by malept** [comment]
This and all other PRs here are currently blocked on getting the gitbook ↔️ GitHub sync fixed.

**Comment by mahnunchik** [comment]
@malept any news?

**Comment by malept** [comment]
Blocked by #11

**Comment by mahnunchik** [comment]
It seems it could be merged?

**Comment by mahnunchik** [comment]
Updated PR https://github.com/electron-userland/electron-forge/pull/2100

**Review by georgexu99 — APPROVED** [review]

**Pull request merged**
