### PR TITLE
docs: migrate forge-specific docs from electronjs.org

### PR DESCRIPTION
**Pull request by georgexu99**
issue: https://github.com/electron-userland/electron-forge/issues/1836#issuecomment-660580058

@erickzhao recently wrote two tutorials regarding how applications can be packaged, published and updated with forge. These should also live within forge's documentation thus have been duplicated and copied over. Within the packaging tutorial, a reference to how to create app icons is added as a hint.

Forge-specific code signing tutorial steps have been  refactored into their own tutorials and moved to their respective windows and macOS forge documentation homes. The sidebar has been updated with these tutorials, in addition to the new icon tutorial.

### CODE REVIEW

**Comment by malept** [comment]
I'm skeptical that we'd want to have duplicate content in both the official Electron docs and the Electron Forge docs. This effectively doubles the maintenance effort when the content needs to be updated. I'd be more inclined to strategically place links and expand on the Electron Guides page.

**Comment by erickzhao** [comment]
@malept this would be moving Forge-specific guides into the Forge part, leaving the non-Forge (e.g. what if you want to package your app manually?) references in the `e/e` docs.

**Comment by malept** [comment]
Hmmm. That is not how I read the PR summary.

In that case, I'm a little worried that this transition will cause the advanced / manual steps to be more emphasized in the official docs, and so we'll have more people (incorrectly) using the advanced / manual methods.

**Comment by georgexu99** [comment]
updated files to eliminate duplicated guides: left @erickzhao 's tutorials back where they originally were.

Forge-specific code-signing guides will be in forge, and will be referenced in the `e/e` docs alongside alternative manual packaging documentation

**Review by VerteDinde — APPROVED** [review]
Looks good - I agree with Mark's comment about maintaining duplicate docs, I think the current state of this PR does a good job of streamlining the tutorials 👍

**Pull request merged**
